cp ~/.Xmodmap .
cp ~/.bashrc .
cp ~/.config/alacritty/alacritty.toml .
cp ~/.config/dunst/dunstrc .
cp ~/.config/i3-scrot.conf .
cp ~/.config/nvim/init.vim .
cp ~/.config/nvim/lua/autumn.lua .
cp ~/.config/picom.conf .
cp ~/.config/polybar/config.ini .
cp ~/.config/rofi/config.rasi .
cp ~/.vimrc .
cp ~/.bars .
cp ~/.pixel-lock .
cp ~/.bashalias .
cp ~/.i3/config .
