
if session.snakepyt_version != (0, 2):
    session.log("this pytrc.py was based on a template generated by an outdated unstable version of snakepyt. it may need to be updated", mode="warning")

session.env.OUT = "/data/0/pyt/out"
session.env.IN = "/data/0/pyt/in"
session.env.SKETCH = "/data/0/pyt/sketch"

session.env.TEMPLATE = "basic"

session.env.PYTHON_PATH = "/data/0/code/python/snakepyt/.venv/bin/python"

session.env.LLM_API = "http://localhost:1312"

session.env.EDITOR = "/home/ponder/ponder/neovide-launcher"

session.favorite_dirs = {
    "data0": "/data/0",
    "data1": "/data/1",
    "data2": "/data/2",
    "ssd0": "/ssd/0",
    "pyt": "/data/0/code/python/snakepyt",
    "out": "/data/0/pyt/out",
    "in": "/data/0/pyt/in",
    "code": "/data/0/code",
    "media": "/data/0/media",
    "crone": "/data/0/code/c/crone",
    "dots": "/home/ponder/ponder/dots"
}

session.favorite_files = {
    "i3config": "/home/ponder/.i3/config",
    "pytrc": "/home/ponder/.config/snakepyt/pytrc.py"
}

@command("llms")
def cmd_llama_server(session, args):
    import subprocess

    subprocess.Popen(
        ["alacritty", "--working-directory", "/ssd/0/llm", "-e", "bash", "-c", "./launch; exec bash"],
        start_new_session=True
    )
    session.log("llama launched!")


